Make run_FUBAR script fail when the errors.log file is produced by FUBAR
This way the pipeline task fails and tasks depending on it are aborted by Compi.

diff --git a/resources/scripts/run_FUBAR b/resources/scripts/run_FUBAR
--- a/resources/scripts/run_FUBAR
+++ b/resources/scripts/run_FUBAR
@@ -25,3 +25,9 @@ cd $5/$2/$3/$1
 cat ${HYPHY_SETTINGS_FILE} | HYPHYMP > $5/$4/$1
 
 rm -f $5/$2/$1.fubar.cache $5/$2/$1.FUBAR.json
+
+if [ -f "errors.log" ]; then
+    echo -e "\nError in fubar-run, showing errors.log:\n"
+    cat errors.log
+    exit 1
+fi
